# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5e4d3226a22a0333453ce548453a94dab4cac2d355c777d1b3da5a647c3645e55d4b3612da7bed103b7d42a2b252c019d9116a380ff8b61d491420e9bba0ca

test:
  secret_key_base: 16a7d942e76c7a989a1e4ae7b010ecbd773fd8cdb4465054733c8e73e4ebd95cb04f690d04efeb25f7211e13edf2f3541eb768ef3cfcead1380520a14ba568c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
